rand singers

for (let i = 0; i < collection.length; i++) {
        console.log(collection[i]);
      }
      
      [
    "Mary J. Blige",
    "Steven Tyler",
    "Stevie Nicks",
    "Joe Cocker",
    "B.B. King",
    "Patti LaBelle",
    "Karen Carpenter",
    "Annie Lennox",
    "Morrissey",
    "Levon Helm",
    "The Everly Brothers",
    "Solomon Burke",
    "Willie Nelson",
    "Don Henley",
    "Art Garfunkel",
    "Sam Moore",
    "Darlene Love",
    "Patti Smith",
    "Tom Waits",
    "John Lee Hooker",
    "Frankie Valli",
    "Mariah Carey",
    "Sly Stone",
    "Merle Haggard",
    "Steve Perry",
    "Iggy Pop",
    "James Taylor",
    "Dolly Parton",
    "John Fogerty",
    "Toots Hibbert",
    "Gregg Allman",
    "Ronnie Spector",
    "Wilson Pickett",
    "Jerry Lee Lewis",
    "Thom Yorke",
    "David Ruffin",
    "Axl Rose",
    "Dion",
    "Lou Reed",
    "Roger Daltrey",
    "Björk",
    "Rod Stewart",
    "Christina Aguilera",
    "Eric Burdon",
    "Mavis Staples",
    "Paul Rodgers",
    "Luther Vandross",
    "Muddy Waters",
    "Brian Wilson",
    "Gladys Knight"
]
